Update create-release.yml

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -30,7 +30,9 @@ jobs:
           minor=$(echo $version | cut -d. -f2)
           patch=$(echo $version | cut -d. -f3 | cut -d- -f1)
           new_version="${major}.${minor}.0-RC.0"
+          branch_name="${major}.${minor}.0"
           echo "VERSION=$new_version" >> $GITHUB_ENV
+          echo "NAME=$branch_name" >> $GITHUB_ENV
           echo "::set-output name=VERSION::$new_version"
 
       - name: Configure git
@@ -40,10 +42,10 @@ jobs:
 
       - name: Create and push new branch
         run: |
-          new_version=${{ env.VERSION }}
-          echo "Creating and pushing new branch release/v$new_version"
-          git checkout -b release/v$new_version || { echo "ERROR: Branch creation failed"; exit 1; }
-          git push origin release/v$new_version --force || { echo "ERROR: Push failed"; exit 1; }
+          name=${{ env.NAME }}
+          echo "Creating and pushing new branch release/v$name"
+          git checkout -b release/v$name || { echo "ERROR: Branch creation failed"; exit 1; }
+          git push origin release/v$name --force || { echo "ERROR: Push failed"; exit 1; }
 
       - name: Get latest commit SHA
         id: get_commit_sha
