Update create-release-pr.yml

diff --git a/.github/workflows/create-release-pr.yml b/.github/workflows/create-release-pr.yml
--- a/.github/workflows/create-release-pr.yml
+++ b/.github/workflows/create-release-pr.yml
@@ -9,14 +9,14 @@ jobs:
 
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v3  # Use the latest version compatible with Node.js 20
+        uses: actions/checkout@v3
         with:
           ref: develop
 
       - name: Set up Node.js
-        uses: actions/setup-node@v2
+        uses: actions/setup-node@v4
         with:
-          node-version: '16'
+          node-version-file: '.nvmrc'
 
       - name: Read package.json version
         id: read_version
@@ -24,42 +24,46 @@ jobs:
           # Print the current directory and list files for debugging
           pwd
           ls -la
-          
+
           # Read and print the current version from package.json
           version=$(node -p "require('./package.json').version")
           echo "Current version: $version"
-          
+
           # Extract version components and increment minor version
           major=$(echo $version | cut -d. -f1)
           minor=$(echo $version | cut -d. -f2)
           patch=$(echo $version | cut -d. -f3 | cut -d- -f1)
           echo "Extracted version - Major: $major, Minor: $minor, Patch: $patch"
-          
+
           new_minor=$((minor + 1))
           new_version="${major}.${new_minor}.0"
           echo "New version: $new_version"
-          
-          # Set the new version in an environment file
+
+          # Check if VERSION environment variable is set
           echo "VERSION=$new_version" >> $GITHUB_ENV
+          if [ -z "$new_version" ]; then
+            echo "ERROR: Version could not be determined."
+            exit 1
+          fi
 
       - name: Configure git
         run: |
           git config --global user.name 'github-actions[bot]'
           git config --global user.email 'github-actions[bot]@users.noreply.github.com'
-          git status
+          git status || exit 1
 
       - name: Create new branch
         id: create_branch
         run: |
           new_version=${{ env.VERSION }}
           echo "Creating new branch release/v$new_version"
-          git checkout -b release/v$new_version || exit 1
+          git checkout -b release/v$new_version || { echo "ERROR: Branch creation failed"; exit 1; }
 
       - name: Push new branch
         run: |
           new_version=${{ env.VERSION }}
           echo "Pushing new branch release/v$new_version"
-          git push origin release/v$new_version || exit 1
+          git push origin release/v$new_version || { echo "ERROR: Push failed"; exit 1; }
 
       - name: Create Pull Request
         uses: peter-evans/create-pull-request@v5
