Update create-release-pr.yml

diff --git a/.github/workflows/create-release-pr.yml b/.github/workflows/create-release-pr.yml
--- a/.github/workflows/create-release-pr.yml
+++ b/.github/workflows/create-release-pr.yml
@@ -48,24 +48,12 @@ jobs:
           git config --global user.email 'github-actions[bot]@users.noreply.github.com'
           git status
 
-      - name: Fetch latest changes
-        run: |
-          git fetch origin
-          git checkout develop
-          git pull origin develop
-
-      - name: Create new branch
-        id: create_branch
+      - name: Create and push new branch
         run: |
           new_version=${{ env.VERSION }}
-          echo "Creating new branch release/v$new_version"
+          echo "Creating and pushing new branch release/v$new_version"
           git checkout -b release/v$new_version || { echo "ERROR: Branch creation failed"; exit 1; }
-
-      - name: Push new branch
-        run: |
-          new_version=${{ env.VERSION }}
-          echo "Pushing new branch release/v$new_version"
-          git push origin release/v$new_version || { echo "ERROR: Push failed"; exit 1; }
+          git push origin release/v$new_version --force || { echo "ERROR: Push failed"; exit 1; }
 
       - name: Create Pull Request
         uses: peter-evans/create-pull-request@v5
