Update create-release.yml

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -9,6 +9,7 @@ jobs:
 
     outputs:
       version: ${{ steps.read_version.outputs.VERSION }}
+      branch_name: ${{ steps.read_version.outputs.BRANCH_NAME }}
       commit_sha: ${{ steps.get_commit_sha.outputs.COMMIT_SHA }}
 
     steps:
@@ -29,11 +30,12 @@ jobs:
           major=$(echo $version | cut -d. -f1)
           minor=$(echo $version | cut -d. -f2)
           patch=$(echo $version | cut -d. -f3 | cut -d- -f1)
-          new_version="${major}.${minor}.0-RC.0"
-          branch_name="${major}.${minor}.0"
+          new_version="${major}.${minor}.${patch}-RC.0"
+          branch_name="release/v${major}.${minor}.${patch}
           echo "VERSION=$new_version" >> $GITHUB_ENV
-          echo "NAME=$branch_name" >> $GITHUB_ENV
+          echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV
           echo "::set-output name=VERSION::$new_version"
+          echo "::set-output name=BRANCH_NAME::$branch_name"
 
       - name: Configure git
         run: |
@@ -42,10 +44,10 @@ jobs:
 
       - name: Create and push new branch
         run: |
-          name=${{ env.NAME }}
-          echo "Creating and pushing new branch release/v$name"
-          git checkout -b release/v$name || { echo "ERROR: Branch creation failed"; exit 1; }
-          git push origin release/v$name --force || { echo "ERROR: Push failed"; exit 1; }
+          name=${{ env.BRANCH_NAME }}
+          echo "Creating and pushing new branch $name"
+          git checkout -b $name || { echo "ERROR: Branch creation failed"; exit 1; }
+          git push origin $name --force || { echo "ERROR: Push failed"; exit 1; }
 
       - name: Get latest commit SHA
         id: get_commit_sha
@@ -96,7 +98,7 @@ jobs:
       - name: Checkout Release Branch
         uses: actions/checkout@v3
         with:
-          ref: release/v${{ needs.create-release-branch.outputs.version }}
+          ref: ${{ needs.create-release-branch.outputs.branch_name }}
 
       - name: 📦 Install dependencies
         run: npm install
